// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-apostilas.ts
import { createClient } from "npm:@supabase/supabase-js@^2.102.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_apostilas_default = defineTool({
  name: "list_apostilas",
  title: "Listar apostilas",
  description: "Lista apostilas publicadas vis\xEDveis para o usu\xE1rio autenticado, opcionalmente filtradas por disciplina/categoria ou busca textual no t\xEDtulo.",
  inputSchema: {
    search: z.string().optional().describe("Filtro textual no t\xEDtulo."),
    category: z.string().optional().describe("Categoria/disciplina."),
    limit: z.number().int().min(1).max(50).optional().describe("M\xE1ximo de itens (padr\xE3o 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    let q = sb(ctx).from("apostilas").select("id,title,category,course,semester,published,updated_at").eq("published", true).order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (search) q = q.ilike("title", `%${search}%`);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-apostila.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.102.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_apostila_default = defineTool2({
  name: "get_apostila",
  title: "Ler apostila",
  description: "Retorna o conte\xFAdo completo (markdown/HTML) e metadados de uma apostila pelo id.",
  inputSchema: {
    id: z2.string().uuid().describe("UUID da apostila.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const { data, error } = await sb2(ctx).from("apostilas").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Apostila n\xE3o encontrada" }], isError: true };
    return {
      content: [{ type: "text", text: `# ${data.title}

${data.content ?? ""}` }],
      structuredContent: { apostila: data }
    };
  }
});

// src/lib/mcp/tools/list-upcoming-exams.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.102.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_upcoming_exams_default = defineTool3({
  name: "list_upcoming_exams",
  title: "Pr\xF3ximas provas e eventos",
  description: "Lista os pr\xF3ximos eventos do calend\xE1rio acad\xEAmico (provas, entregas, avisos com data) a partir de hoje.",
  inputSchema: {
    days: z3.number().int().min(1).max(180).optional().describe("Janela em dias a partir de hoje (padr\xE3o 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const today = (/* @__PURE__ */ new Date()).toISOString();
    const end = new Date(Date.now() + (days ?? 30) * 864e5).toISOString();
    const { data, error } = await sb3(ctx).from("calendar_events").select("id,title,subject,event_type,event_date,description").gte("event_date", today).lte("event_date", end).order("event_date", { ascending: true }).limit(50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-announcements.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.102.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_announcements_default = defineTool4({
  name: "list_announcements",
  title: "Avisos recentes",
  description: "Lista os avisos/comunicados mais recentes da plataforma.",
  inputSchema: {
    limit: z4.number().int().min(1).max(30).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const { data, error } = await sb4(ctx).from("announcements").select("id,title,category,content,created_at").eq("published", true).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-free-courses.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.102.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_free_courses_default = defineTool5({
  name: "list_free_courses",
  title: "Cursos gratuitos com horas complementares",
  description: "Lista cursos gratuitos ativos cadastrados pelo administrador (com link e carga hor\xE1ria).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const { data, error } = await sb5(ctx).from("free_courses").select("id,title,provider,link_url,workload,area,description,certificate").eq("is_active", true).order("sort_order", { ascending: true }).limit(100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-flashcards.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.102.1";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^4.4.3";
function sb6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_flashcards_default = defineTool6({
  name: "list_my_flashcards",
  title: "Meus flashcards",
  description: "Lista os flashcards do usu\xE1rio autenticado, opcionalmente filtrando por disciplina.",
  inputSchema: {
    apostila_id: z5.string().uuid().optional(),
    limit: z5.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ apostila_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    let q = sb6(ctx).from("flashcards").select("id,front,back,apostila_id,difficulty,next_review,created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 30);
    if (apostila_id) q = q.eq("apostila_id", apostila_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-flashcard.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.102.1";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^4.4.3";
function sb7(ctx) {
  return createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_flashcard_default = defineTool7({
  name: "create_flashcard",
  title: "Criar flashcard",
  description: "Cria um novo flashcard (frente/verso) para o usu\xE1rio autenticado.",
  inputSchema: {
    front: z6.string().trim().min(1),
    back: z6.string().trim().min(1),
    apostila_id: z6.string().uuid().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async ({ front, back, apostila_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const { data, error } = await sb7(ctx).from("flashcards").insert({ user_id: ctx.getUserId(), front, back, apostila_id: apostila_id ?? null }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Flashcard criado (${data?.id}).` }],
      structuredContent: { flashcard: data }
    };
  }
});

// src/lib/mcp/tools/my-progress.ts
import { createClient as createClient8 } from "npm:@supabase/supabase-js@^2.102.1";
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.24.0";
function sb8(ctx) {
  return createClient8(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var my_progress_default = defineTool8({
  name: "my_progress",
  title: "Meu progresso",
  description: "Retorna o resumo de gamifica\xE7\xE3o do usu\xE1rio: XP, n\xEDvel, streak e apostilas conclu\xEDdas.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    const client = sb8(ctx);
    const uid = ctx.getUserId();
    const [xp, streak, completions] = await Promise.all([
      client.from("user_xp").select("*").eq("user_id", uid).maybeSingle(),
      client.from("study_streaks").select("*").eq("user_id", uid).maybeSingle(),
      client.from("apostila_completions").select("apostila_id", { count: "exact", head: true }).eq("user_id", uid)
    ]);
    const summary = {
      xp: xp.data ?? null,
      streak: streak.data ?? null,
      completed_apostilas: completions.count ?? 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gynguskgysompgcajunc";
var mcp_default = defineMcp({
  name: "decode-analytics-mcp",
  title: "Decode Analytics Academy",
  version: "0.1.0",
  instructions: "Ferramentas do Decode Analytics Academy: consulte apostilas publicadas, pr\xF3ximas provas, avisos, cursos gratuitos, seus flashcards e progresso. Use `list_apostilas` para descobrir conte\xFAdo, `get_apostila` para ler o material completo, e `create_flashcard` para salvar cards de estudo. Todas as a\xE7\xF5es s\xE3o executadas como o usu\xE1rio autenticado (RLS aplicado).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_apostilas_default,
    get_apostila_default,
    list_upcoming_exams_default,
    list_announcements_default,
    list_free_courses_default,
    list_my_flashcards_default,
    create_flashcard_default,
    my_progress_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
