-- Optimize Row Level Security auth checks by caching request-stable auth.uid() evaluation.
-- No authorization predicate is changed; direct auth.uid() calls are wrapped in SELECT.
alter policy "Admins can view all access logs" on public.access_logs using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Users can insert their own access logs" on public.access_logs with check (((select auth.uid()) = user_id));
alter policy "Users can insert own activity logs" on public.activity_logs with check ((((select auth.uid()) = user_id) OR has_role((select auth.uid()), 'admin'::app_role)));
alter policy "Admins view ad clicks" on public.ad_clicks using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Users can insert own ad clicks" on public.ad_clicks with check (((user_id IS NULL) OR ((select auth.uid()) = user_id)));
alter policy "Admins view ad views" on public.ad_views using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Users can insert own ad views" on public.ad_views with check (((user_id IS NULL) OR ((select auth.uid()) = user_id)));
alter policy "Admins can view all logs" on public.admin_audit_logs using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins can manage ads" on public.ads using (has_role((select auth.uid()), 'admin'::app_role)) with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Anyone can view active ads" on public.ads using (((is_active = true) OR has_role((select auth.uid()), 'admin'::app_role)));
alter policy "Users can manage own annotations" on public.annotations using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
alter policy "Admins can manage announcements" on public.announcements using (has_role((select auth.uid()), 'admin'::app_role)) with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Authenticated can view published announcements" on public.announcements using (((published = true) OR has_role((select auth.uid()), 'admin'::app_role)));
alter policy "Users can insert own answers" on public.answers with check (((select auth.uid()) = user_id));
alter policy "Users can view own answers" on public.answers using (((select auth.uid()) = user_id));
alter policy "Scoped visibility for apostila_chapters" on public.apostila_chapters using ((has_role((select auth.uid()), 'admin'::app_role) OR (EXISTS ( SELECT 1
   FROM (apostila_modules m
     JOIN apostilas a ON ((a.id = m.apostila_id)))
  WHERE ((m.id = apostila_chapters.module_id) AND (a.published = true) AND (((get_content_scope((select auth.uid())) = 'full'::text) AND ((a.category IS NULL) OR (a.category <> ALL (ARRAY['ENEM'::text, 'Simulados ENEM'::text])))) OR ((get_content_scope((select auth.uid())) = 'enem_only'::text) AND (a.category = ANY (ARRAY['ENEM'::text, 'Simulados ENEM'::text])))))))));
alter policy "Users can delete own apostila chats" on public.apostila_chats using (((select auth.uid()) = user_id));
alter policy "Users can insert own apostila chats" on public.apostila_chats with check (((select auth.uid()) = user_id));
alter policy "Users can view own apostila chats" on public.apostila_chats using (((select auth.uid()) = user_id));
alter policy "Authenticated users can insert comments v2" on public.apostila_comments with check (((select auth.uid()) = user_id));
alter policy "Users can delete their own comments" on public.apostila_comments using (((select auth.uid()) = user_id));
alter policy "Users can update their own comments" on public.apostila_comments using (((select auth.uid()) = user_id));
alter policy "Authenticated users manage own completions v2" on public.apostila_completions using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
alter policy "Users can add own apostila favorites" on public.apostila_favorites with check (((select auth.uid()) = user_id));
alter policy "Users can remove own apostila favorites" on public.apostila_favorites using (((select auth.uid()) = user_id));
alter policy "Users can view own apostila favorites" on public.apostila_favorites using (((select auth.uid()) = user_id));
alter policy "Admins can manage generation jobs" on public.apostila_generation_jobs using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Users manage own bookmarks" on public.apostila_lesson_bookmarks using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
alter policy "Users manage own notes" on public.apostila_lesson_notes using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
alter policy "Users manage own lesson progress" on public.apostila_lesson_progress using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
alter policy "Users can delete their own likes" on public.apostila_likes using (((select auth.uid()) = user_id));
alter policy "Users can insert their own likes" on public.apostila_likes with check (((select auth.uid()) = user_id));
alter policy "Admins can view apostila operation logs" on public.apostila_operation_logs using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Authenticated users can create own shares v2" on public.apostila_shares with check (((select auth.uid()) = created_by));
alter policy "Owners or admins can view shares" on public.apostila_shares using ((((select auth.uid()) = created_by) OR has_role((select auth.uid()), 'admin'::app_role)));
alter policy "Users can delete their own shares" on public.apostila_shares using (((select auth.uid()) = created_by));
alter policy "Authenticated can insert summaries" on public.apostila_summaries with check (((select auth.uid()) = generated_by));
alter policy "Authenticated can update summaries" on public.apostila_summaries using (((select auth.uid()) IS NOT NULL)) with check (((select auth.uid()) IS NOT NULL));
alter policy "Admins can update apostila validation alerts" on public.apostila_validation_alerts using (has_role((select auth.uid()), 'admin'::app_role)) with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins can view apostila validation alerts" on public.apostila_validation_alerts using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins can update apostila validation issues" on public.apostila_validation_issues using (has_role((select auth.uid()), 'admin'::app_role)) with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins can view apostila validation issues" on public.apostila_validation_issues using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins can view apostila validation runs" on public.apostila_validation_runs using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins can manage version history" on public.apostila_version_history using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Authenticated users can insert views v2" on public.apostila_views with check (((user_id IS NULL) OR ((select auth.uid()) = user_id)));
alter policy "Users can view own apostila views" on public.apostila_views using ((((select auth.uid()) = user_id) OR has_role((select auth.uid()), 'admin'::app_role)));
alter policy "Admins can manage app_settings" on public.app_settings using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "app_settings admin delete" on public.app_settings using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "app_settings admin insert" on public.app_settings with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "app_settings admin update" on public.app_settings using (has_role((select auth.uid()), 'admin'::app_role)) with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins can see all audit logs" on public.audit_logs using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Users can insert their own logs" on public.audit_logs with check (((select auth.uid()) = user_id));
alter policy "Admins can manage badges" on public.badges using (has_role((select auth.uid()), 'admin'::app_role)) with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins can delete books" on public.books using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins can insert books" on public.books with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins can update books" on public.books using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Authenticated can view published books" on public.books using (((published = true) OR has_role((select auth.uid()), 'admin'::app_role)));
alter policy "Authenticated users manage own grades v2" on public.calculator_grades using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
alter policy "Admins can delete events" on public.calendar_events using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins can insert events" on public.calendar_events with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins can update events" on public.calendar_events using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins or owners can delete comments" on public.comments using ((has_role((select auth.uid()), 'admin'::app_role) OR ((select auth.uid()) = user_id)));
alter policy "Users can insert own comments" on public.comments with check (((select auth.uid()) = user_id));
alter policy "Users can update own comments" on public.comments using (((select auth.uid()) = user_id));
alter policy "Admins can manage channels" on public.community_channels using (has_role((select auth.uid()), 'admin'::app_role)) with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Users can like" on public.community_post_likes with check (((select auth.uid()) = user_id));
alter policy "Users can unlike" on public.community_post_likes using (((select auth.uid()) = user_id));
alter policy "Admins can manage all posts" on public.community_posts using (has_role((select auth.uid()), 'admin'::app_role)) with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Users can delete own posts" on public.community_posts using (((select auth.uid()) = user_id));
alter policy "Users can insert own posts" on public.community_posts with check (((select auth.uid()) = user_id));
alter policy "Users can update own posts" on public.community_posts using (((select auth.uid()) = user_id));
alter policy "Admins or owners can delete replies" on public.community_replies using ((has_role((select auth.uid()), 'admin'::app_role) OR ((select auth.uid()) = user_id)));
alter policy "Users can insert own replies" on public.community_replies with check (((select auth.uid()) = user_id));
alter policy "Users can insert their own compliance logs" on public.compliance_logs with check (((select auth.uid()) = user_id));
alter policy "Users can view their own compliance logs" on public.compliance_logs using (((select auth.uid()) = user_id));
alter policy "Users can view own downloads" on public.downloads using (((select auth.uid()) = user_id));
alter policy "Admins can read ella audit log" on public.ella_audit_log using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins podem ver os registros de uso" on public.ella_usage_events using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins or owners can view Ella blocks" on public.ella_user_blocks using ((has_role((select auth.uid()), 'admin'::app_role) OR (user_id = (select auth.uid()))));
alter policy "Admins view exercise answer access log" on public.exercise_answer_access_log using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins can manage fixed apostilas" on public.fixed_apostilas using (has_role((select auth.uid()), 'admin'::app_role)) with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Users can manage own flashcards" on public.flashcards using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
alter policy "Usuários podem atualizar seus próprios flashcards" on public.flashcards using (((select auth.uid()) = user_id));
alter policy "Usuários podem criar seus próprios flashcards" on public.flashcards with check (((select auth.uid()) = user_id));
alter policy "Usuários podem deletar seus próprios flashcards" on public.flashcards using (((select auth.uid()) = user_id));
alter policy "Usuários podem ver seus próprios flashcards" on public.flashcards using (((select auth.uid()) = user_id));
alter policy "Admins can delete free courses" on public.free_courses using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins can insert free courses" on public.free_courses with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins can update free courses" on public.free_courses using (has_role((select auth.uid()), 'admin'::app_role)) with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Anyone can view active free courses" on public.free_courses using (((is_active = true) OR has_role((select auth.uid()), 'admin'::app_role)));
alter policy "Admins can manage jobs" on public.jobs using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Anyone can view active jobs" on public.jobs using (((is_active = true) OR has_role((select auth.uid()), 'admin'::app_role)));
alter policy "Admins can manage maintenance logs" on public.maintenance_logs using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Authenticated users manage own favorites v2" on public.material_favorites using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
alter policy "Admins can manage materials" on public.materials using (has_role((select auth.uid()), 'admin'::app_role)) with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Authenticated can view scoped materials" on public.materials using ((has_role((select auth.uid()), 'admin'::app_role) OR (EXISTS ( SELECT 1
   FROM (apostila_materials am
     JOIN apostilas a ON ((a.id = am.apostila_id)))
  WHERE ((am.material_id = materials.id) AND (a.published = true) AND (((get_content_scope((select auth.uid())) = 'full'::text) AND ((a.category IS NULL) OR (a.category <> ALL (ARRAY['ENEM'::text, 'Simulados ENEM'::text])))) OR ((get_content_scope((select auth.uid())) = 'enem_only'::text) AND (a.category = ANY (ARRAY['ENEM'::text, 'Simulados ENEM'::text]))))))) OR (EXISTS ( SELECT 1
   FROM categories c
  WHERE ((c.id = materials.category_id) AND (((get_content_scope((select auth.uid())) = 'enem_only'::text) AND (c.slug ~~ 'enem-%'::text)) OR ((get_content_scope((select auth.uid())) = 'full'::text) AND (c.slug !~~ 'enem-%'::text))))))));
alter policy "Authenticated can create mentions as author" on public.mention_notifications with check ((((select auth.uid()) = author_id) AND (author_id <> recipient_id)));
alter policy "Recipients can delete own mentions" on public.mention_notifications using (((select auth.uid()) = recipient_id));
alter policy "Recipients can update own mentions" on public.mention_notifications using (((select auth.uid()) = recipient_id));
alter policy "Recipients can view own mentions" on public.mention_notifications using (((select auth.uid()) = recipient_id));
alter policy "Users can manage contents of their own pages" on public.notebook_page_contents using ((EXISTS ( SELECT 1
   FROM (notebook_pages
     JOIN notebooks ON ((notebooks.id = notebook_pages.notebook_id)))
  WHERE ((notebook_pages.id = notebook_page_contents.page_id) AND (notebooks.user_id = (select auth.uid()))))));
alter policy "Users can manage pages of their own notebooks" on public.notebook_pages using ((EXISTS ( SELECT 1
   FROM notebooks
  WHERE ((notebooks.id = notebook_pages.notebook_id) AND (notebooks.user_id = (select auth.uid()))))));
alter policy "Users can manage their own notebooks" on public.notebooks using (((select auth.uid()) = user_id));
alter policy "Admins insert notifications v2" on public.notifications with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Users delete own notifications v2" on public.notifications using (((select auth.uid()) = user_id));
alter policy "Users update own notifications v2" on public.notifications using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
alter policy "Users view own notifications v2" on public.notifications using (((select auth.uid()) = user_id));
alter policy "Users manage their own study plans" on public.planos_estudo using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
alter policy "Users manage their own study plan tasks" on public.planos_estudo_tarefas using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
alter policy "Users create their own study plan versions" on public.planos_estudo_versoes with check (((select auth.uid()) = user_id));
alter policy "Users delete their own study plan versions" on public.planos_estudo_versoes using (((select auth.uid()) = user_id));
alter policy "Users read their own study plan versions" on public.planos_estudo_versoes using (((select auth.uid()) = user_id));
alter policy "Authenticated users manage own pb bookmarks v2" on public.playbooks_bookmarks using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
alter policy "Authenticated users manage own pb highlights v2" on public.playbooks_highlights using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
alter policy "Authenticated users manage own pb notes v2" on public.playbooks_notes using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
alter policy "Authenticated users manage own pomodoro sessions v2" on public.pomodoro_sessions using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
alter policy "Admins can delete profiles" on public.profiles using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins or owners can update profiles" on public.profiles using ((has_role((select auth.uid()), 'admin'::app_role) OR ((select auth.uid()) = user_id))) with check ((has_role((select auth.uid()), 'admin'::app_role) OR ((select auth.uid()) = user_id)));
alter policy "Admins or owners can view profiles" on public.profiles using ((has_role((select auth.uid()), 'admin'::app_role) OR ((select auth.uid()) = user_id)));
alter policy "Users can insert own profile" on public.profiles with check (((select auth.uid()) = user_id));
alter policy "users manage own push subs - delete" on public.push_subscriptions using (((select auth.uid()) = user_id));
alter policy "users manage own push subs - insert" on public.push_subscriptions with check (((select auth.uid()) = user_id));
alter policy "users manage own push subs - select" on public.push_subscriptions using (((select auth.uid()) = user_id));
alter policy "Admins can manage questions" on public.quiz_questions using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Users can manage their own submissions" on public.quiz_submissions using (((select auth.uid()) = user_id));
alter policy "Admins can manage everything" on public.quizzes using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Authenticated users can read quizzes" on public.quizzes using (((select auth.uid()) IS NOT NULL));
alter policy "Authenticated users manage own reading progress v2" on public.reading_progress using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
alter policy "Admins or owners can view respostas_foto" on public.respostas_foto using ((has_role((select auth.uid()), 'admin'::app_role) OR ((select auth.uid()) = user_id)));
alter policy "Users can insert own respostas_foto" on public.respostas_foto with check (((select auth.uid()) = user_id));
alter policy "Users can update own respostas_foto" on public.respostas_foto using (((select auth.uid()) = user_id));
alter policy "Admins can delete feeds" on public.rss_feeds using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins can insert feeds" on public.rss_feeds with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins can update feeds" on public.rss_feeds using (has_role((select auth.uid()), 'admin'::app_role)) with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins can insert validation history v2" on public.rss_validation_history with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins can read validation history v2" on public.rss_validation_history using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins can view security logs" on public.security_audit_logs using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins can acknowledge security notifications" on public.security_notifications using (has_role((select auth.uid()), 'admin'::app_role)) with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins can view security notifications" on public.security_notifications using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins manage funnel thresholds" on public.sponsor_funnel_thresholds using (has_role((select auth.uid()), 'admin'::app_role)) with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins manage sponsor lead events" on public.sponsor_lead_events using (has_role((select auth.uid()), 'admin'::app_role)) with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins delete sponsor leads" on public.sponsor_leads using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins manage sponsor leads" on public.sponsor_leads using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins update sponsor leads" on public.sponsor_leads using (has_role((select auth.uid()), 'admin'::app_role)) with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Users can create own student notes" on public.student_notes with check (((select auth.uid()) = user_id));
alter policy "Users can delete own student notes" on public.student_notes using (((select auth.uid()) = user_id));
alter policy "Users can update own student notes" on public.student_notes using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
alter policy "Users can view own student notes" on public.student_notes using (((select auth.uid()) = user_id));
alter policy "Users manage own study goals" on public.study_goals using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
alter policy "Users read own study history" on public.study_history using (((select auth.uid()) = user_id));
alter policy "Users read own study milestones" on public.study_milestones using (((select auth.uid()) = user_id));
alter policy "Users manage own study plans" on public.study_plans using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
alter policy "Authenticated users manage own streaks v2" on public.study_streaks using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
alter policy "Admins can manage testimonials" on public.testimonials using (has_role((select auth.uid()), 'admin'::app_role)) with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Users can delete own testimonial" on public.testimonials using (((select auth.uid()) = user_id));
alter policy "Users can submit own testimonial" on public.testimonials with check (((select auth.uid()) = user_id));
alter policy "Users can view own testimonials" on public.testimonials using (((select auth.uid()) = user_id));
alter policy "Admins can update tira-duvidas" on public.tira_duvidas using (has_role((select auth.uid()), 'admin'::app_role)) with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Admins or owners can view tira-duvidas" on public.tira_duvidas using ((has_role((select auth.uid()), 'admin'::app_role) OR ((select auth.uid()) = user_id)));
alter policy "Users create own tira-duvidas" on public.tira_duvidas with check (((select auth.uid()) = user_id));
alter policy "Users delete own tira-duvidas" on public.tira_duvidas using (((select auth.uid()) = user_id));
alter policy "Authenticated users can insert own badges v2" on public.user_badges with check (((select auth.uid()) = user_id));
alter policy "Authenticated users can view own badges v2" on public.user_badges using ((((select auth.uid()) = user_id) OR has_role((select auth.uid()), 'admin'::app_role)));
alter policy "Admins can manage roles v2" on public.user_roles using (has_role((select auth.uid()), 'admin'::app_role)) with check (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Users can view own roles v2" on public.user_roles using ((((select auth.uid()) = user_id) OR has_role((select auth.uid()), 'admin'::app_role)));
alter policy "Users can update their own streaks" on public.user_streaks using (((select auth.uid()) = user_id));
alter policy "Authenticated users can insert own xp v2" on public.user_xp with check (((select auth.uid()) = user_id));
alter policy "Users can view own xp" on public.user_xp using ((((select auth.uid()) = user_id) OR has_role((select auth.uid()), 'admin'::app_role)));
alter policy "Admins view all simulado answers" on public.weekly_simulado_answers using (has_role((select auth.uid()), 'admin'::app_role));
alter policy "Authenticated users manage own simulado answers v2" on public.weekly_simulado_answers using (((select auth.uid()) = user_id)) with check (((select auth.uid()) = user_id));
alter policy "Users view own simulados" on public.weekly_simulados using ((has_role((select auth.uid()), 'admin'::app_role) OR ((select auth.uid()) = user_id)));
alter policy "Users can view own XP award events" on public.xp_award_events using (((select auth.uid()) = user_id));