-- Migration: humanize_all_jobs_descriptions
-- Description: Replaces job descriptions with long, human-written prose, completely free of Markdown asterisks, with spelled-out academic courses and highlighted salary/schedule/model info.

UPDATE public.jobs
SET description = 'A Honda está com inscrições abertas para o Programa de Estágio de Inverno na cidade de São Paulo, com escritório localizado próximo ao Shopping Morumbi, à estação Morumbi da CPTM e à estação Borba Gato do metrô. A modalidade é híbrida, oferecendo flexibilidade para o estudante. As oportunidades abrangem áreas como Tecnologia da Informação, Comercial, Finanças, Controle de Qualidade, Marketing, Relações Públicas e Compras. Para concorrer, é necessário estar regularmente matriculado em cursos superiores de Ciência da Computação, Sistemas de Informação, Engenharia de Computação, Estatística, Matemática ou áreas correlatas, com disponibilidade para estagiar por um período de 24 meses. O estagiário atuará prestando apoio em projetos corporativos, atualização de documentos, planilhas e apresentações gerenciais, acompanhamento de indicadores e relatórios de desempenho, mapeamento e otimização de processos, participação em reuniões estratégicas e treinamentos internos, além de pesquisas e análises com ferramentas corporativas. Como diferenciais, a empresa busca candidatos com bons conhecimentos no Pacote Microsoft Office, especialmente Excel e PowerPoint, boa comunicação verbal e escrita, perfil organizado, atenção aos detalhes, proatividade, pensamento crítico, facilidade para trabalhar em equipe e alta capacidade de adaptabilidade. Um ponto de grande destaque para quem estuda à noite é a carga horária: o programa oferece jornada reduzida e horário compatível, com preferência para o turno das 8h às 15h, totalizando trinta horas semanais, o que garante excelente compatibilidade com aulas noturnas. Os benefícios oferecidos incluem plano de saúde, plano odontológico, programa Wellhub, seguro de vida, programas estruturados de desenvolvimento profissional, vale-refeição, transporte fretado, vale-transporte e estacionamento no local, variando conforme a localidade e a modalidade de atuação.'
WHERE title ILIKE '%Honda%';

UPDATE public.jobs
SET description = 'O J.P. Morgan Chase abriu as inscrições para o Programa de Estágio Brasil Drive The Future, com foco em Technology Roles para o ciclo de novembro de 2026. A vaga é presencial e localizada no escritório de São Paulo, situado no Itaim Bibi, na Avenida Brigadeiro Faria Lima, número 3729. O programa é direcionado a estudantes universitários matriculados em cursos de Ciência da Computação, Engenharia de Computação, Tecnologia da Informação ou áreas afins, que estejam na metade da graduação e com previsão de conclusão a partir de novembro de 2028. Os selecionados farão parte do time global de tecnologia da instituição, recebendo treinamento intensivo, acompanhamento de mentores e forte desenvolvimento profissional prático. Não é exigida experiência profissional anterior, mas o candidato precisa comprovar nível de inglês avançado tanto para conversação quanto para escrita. A jornada de trabalho é de trinta horas semanais, divididas em seis horas diárias com uma hora de intervalo para almoço. Os horários disponíveis para escolha no processo são das 9h às 16h, das 10h às 17h ou das 12h às 19h. Para os estudantes que frequentam a faculdade no período noturno, os turnos das 9h às 16h e das 10h às 17h oferecem excelente compatibilidade com a rotina de estudos. Os valores de bolsa-auxílio e o pacote de benefícios serão detalhados durante as etapas finais do processo seletivo no portal oficial da instituição.'
WHERE title ILIKE '%J.P. Morgan%';

UPDATE public.jobs
SET description = 'O Nubank anunciou o seu Programa de Estágio com foco em Inteligência Artificial, oferecendo uma oportunidade inovadora em tecnologia. O modelo de trabalho é híbrido, exigindo três dias presenciais no escritório e dois dias de trabalho remoto, com vagas disponíveis nas regiões metropolitanas de São Paulo, Campinas, Rio de Janeiro e Belo Horizonte. O programa aceita estudantes matriculados em qualquer curso superior de bacharelado, licenciatura ou tecnólogo, abrangendo perfeitamente estudantes de Ciência da Computação, Sistemas de Informação e Engenharia de Computação. No dia a dia, a pessoa estagiária irá circular por diferentes desafios de inteligência artificial, trabalhando diretamente com agentes inteligentes, modelos de machine learning, grandes volumes de dados, automações de processos, prevenção a fraudes, crédito e soluções que impactam milhões de clientes. Para participar, é fundamental possuir proficiência em inglês em nível avançado, domínio básico ou intermediário em pelo menos uma linguagem de programação como Python, Java, Kotlin, Go, Clojure ou Dart, além de conhecimentos práticos em consultas SQL, noções de machine learning, estatística, conceitos fundamentais de engenharia de software, controle de versão com Git, testes automatizados e organização de código. É um grande diferencial já ter construído soluções utilizando ferramentas de inteligência artificial, APIs, agentes ou pipelines de dados. A carga horária é de trinta horas semanais, correspondendo a seis horas diárias, com duração mínima de dezoito meses. O Nubank oferece flexibilidade para que o estudante consiga cumprir suas responsabilidades acadêmicas sem conflitos com o horário noturno. O pacote de remuneração inclui bolsa-auxílio altamente competitiva no mercado, vale-refeição ou vale-alimentação, vale-transporte, plano médico e odontológico de excelência, seguro de vida, subsídio para despesas de trabalho remoto, assistência psicológica, financeira e jurídica, programa de idiomas, plataforma de aprendizagem e parcerias com redes de academias.'
WHERE title ILIKE '%Nubank%';

UPDATE public.jobs
SET description = 'A DOMO Inovação, atuando como o hub de tecnologia do Banco Mercantil, está com inscrições abertas para a vaga de estágio em Governança de Dados. A oportunidade é na modalidade totalmente remota, permitindo que estudantes de todo o Brasil participem, com inclusão dedicada também para pessoas com deficiência. Os cursos preferenciais para a vaga incluem Ciência da Computação, Sistemas de Informação, Análise e Desenvolvimento de Sistemas, Engenharia de Computação e áreas afins. A pessoa estagiária será responsável por apoiar na padronização de processos corporativos, implementação de boas práticas de governança e gestão de dados, elaboração de documentos técnicos, construção de relatórios gerenciais e indicadores de qualidade, monitoramento da evolução das políticas de dados e atendimento às necessidades analíticas das áreas de negócio. Como requisitos obrigatórios, exige-se domínio prático da linguagem SQL, matrícula ativa em curso superior com disponibilidade para cumprir um ciclo de dois anos de estágio e dedicação de seis horas diárias. Conhecimentos prévios na plataforma Snowflake são considerados um diferencial competitivo importante. A carga horária é de seis horas por dia em horário comercial, sendo recomendado confirmar o alinhamento do turno com as aulas da faculdade. A bolsa-auxílio oferecida é no valor expressivo de R$ 3.000,00 mensais, complementada por benefícios como acesso à Academia Mercantil de Desenvolvimento, seguro de vida e o programa Day Off de folga no aniversário.'
WHERE title ILIKE '%Governança de Dados%' OR title ILIKE '%DOMO%';

UPDATE public.jobs
SET description = 'O Fundo Garantidor de Créditos está com inscrições abertas para o Programa de Estágio em Tecnologia com foco em Operações e SRE. O escritório está localizado em São Paulo, na região da Faria Lima, e o modelo de trabalho é híbrido, combinando três dias de presença no escritório e dois dias de trabalho remoto por semana. O programa é voltado para estudantes de Tecnologia da Informação, Ciência da Computação, Sistemas de Informação, Engenharia de Computação e cursos relacionados. Na rotina de estágio, o estudante irá apoiar ativamente o monitoramento contínuo da disponibilidade e desempenho dos sistemas corporativos, análise de alertas, eventos e métricas de infraestrutura, acompanhamento de incidentes, processos de troubleshooting, automação de tarefas repetitivas, manutenção de painéis e dashboards, organização de logs, elaboração de documentações e runbooks, além de participar de análises pós-incidente. Os requisitos essenciais incluem conhecimentos básicos em infraestrutura de tecnologia, sistemas operacionais Windows e Linux, redes TCP/IP, serviços de DNS, protocolos HTTP e HTTPS, lógica de programação, bancos de dados relacionais e linguagem SQL, além de familiaridade com o ecossistema Microsoft 365. Conhecimentos práticos em Python, PowerShell, computação em nuvem, APIs REST, controle de versão com Git, além de conceitos de ITIL, DevOps e engenharia de confiabilidade (SRE) são tratados como diferenciais de grande valor. A modalidade híbrida oferece flexibilidade para a organização da rotina acadêmica. A empresa oferece um excelente pacote de benefícios, incluindo auxílio refeição no valor de R$ 990,52 mensais, vale-transporte integral, seguro de vida, convênio com o SESC, TotalPass para academias e sessões de ginástica laboral.'
WHERE title ILIKE '%FGC%';

UPDATE public.jobs
SET description = 'A agência AlmapBBDO busca Pessoa Estagiária em Tecnologia para atuar em seu escritório na cidade de São Paulo, operando em modelo de trabalho híbrido. O programa aceita estudantes matriculados em cursos de Sistemas de Informação, Engenharia de Computação, Administração de Empresas e áreas correlatas. A principal missão do estagiário será atuar no suporte técnico de primeiro atendimento aos usuários dos sistemas da agência. As atividades diárias envolvem triagem, classificação e priorização de chamados técnicos, reprodução e documentação detalhada de problemas, acompanhamento dos incidentes até a resolução completa, manutenção de bases de conhecimento, tutoriais e FAQs, treinamento prático de usuários, realização de testes de novas funcionalidades e análise de indicadores de qualidade do suporte. Para se candidatar, é necessário ter disponibilidade para estagiar seis horas por dia em modelo híbrido, excelente habilidade de comunicação interpessoal, organização pessoal, rigor com prazos, postura investigativa para resolução de problemas e sólidos conhecimentos em lógica de programação e arquitetura de sistemas. A carga horária é de seis horas diárias, e o horário exato deve ser alinhado com a equipe para garantir a compatibilidade com o período noturno da faculdade.'
WHERE title ILIKE '%AlmapBBDO%';

UPDATE public.jobs
SET description = 'O Instituto de Pesquisas Eldorado está com inscrições abertas para Estágio em Desenvolvimento Web, com oportunidade na modalidade remota, sendo acessível para estudantes residentes no estado de São Paulo. A vaga é destinada a universitários matriculados em Ciência da Computação, Engenharia de Computação, Sistemas de Informação e áreas correlatas. O estagiário atuará diretamente no desenvolvimento de aplicações web nos fronts e backs de sistemas modernos, criação e manutenção de rotinas de testes automatizados, desenvolvimento voltado para ambientes de computação em nuvem, aplicação de metodologias ágeis como Scrum e Kanban, participação em sessões de code review e colaboração direta no atendimento a demandas de clientes. Os candidatos devem possuir conhecimentos básicos em linguagens e tecnologias como JavaScript, TypeScript, HTML, CSS, SCSS, frameworks modernos, Java, Spring Boot e ferramentas de controle de versão como Git. Vivência prévia com Google Cloud Platform, práticas de engenharia de software e inglês em nível intermediário são considerados grandes diferenciais. A modalidade de trabalho remoto proporciona excelente flexibilidade para estudantes de cursos noturnos, permitindo melhor gestão do tempo entre as aulas e os estudos.'
WHERE title ILIKE '%Desenvolvimento Web%';
