// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const LEGACY_SUPABASE_URL = 'https://gynguskgysompgcajunc.supabase.co';
const ACTIVE_SUPABASE_URL = 'https://wxkkpjpqyrygglbuogsd.supabase.co';
const ACTIVE_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_Zh6H3y8GJ2J_wkRVXxyTng_eylbCAVM';

// Migração de runtime: alguns deploys antigos da Vercel ainda possuem a URL
// legada nas variáveis de ambiente. Mantemos a ponte até a configuração da Vercel
// ser atualizada para o projeto ativo, sem interromper login, apostilas ou Ella.
// Lovable pode publicar o bundle sem injetar as variáveis Vite. Nesse caso,
// usamos o endpoint ativo versionado no código em vez de derrubar o app na carga.
const configuredUrl = import.meta.env.VITE_SUPABASE_URL || ACTIVE_SUPABASE_URL;
const isLegacyDeployment = configuredUrl === LEGACY_SUPABASE_URL;
const SUPABASE_URL = isLegacyDeployment ? ACTIVE_SUPABASE_URL : configuredUrl;
const SUPABASE_PUBLISHABLE_KEY = isLegacyDeployment
  ? ACTIVE_SUPABASE_PUBLISHABLE_KEY
  : (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || ACTIVE_SUPABASE_PUBLISHABLE_KEY);

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Supabase client could not be initialized.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
});
