// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const FALLBACK_SUPABASE_URL = 'https://wxkkpjpqyrygglbuogsd.supabase.co';
// Publishable keys are designed to be embedded in browser bundles.  Keeping
// this fallback prevents a missing Lovable/Vite environment variable from
// throwing during module evaluation and leaving the application as a blank
// screen.  It is restricted to the single active production project.
const FALLBACK_SUPABASE_PUBLISHABLE_KEY =
  'sb_publishable_Zh6H3y8GJ2J_wkRVXxyTng_eylbCAVM';
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim() || FALLBACK_SUPABASE_PUBLISHABLE_KEY;

// O runtime deste projeto deve apontar exclusivamente para o Supabase de produção
// atual. Ignoramos valores Vite legados para evitar que um bundle publicado caia
// silenciosamente no projeto antigo durante a migração.
export const SUPABASE_URL = FALLBACK_SUPABASE_URL;
export { SUPABASE_PUBLISHABLE_KEY };

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Supabase client could not be initialized.');
}

// Todas as falhas do Supabase precisam chegar ao chamador. Transformar uma falha
// de RLS, sessão ou rede em uma lista vazia faz a interface concluir que a
// apostila não tem páginas — e mascara a causa de conteúdo aparentemente sumir.
// As telas de leitura já tratam fontes complementares como opcionais sem ocultar
// o erro da consulta.
const nativeFetch = globalThis.fetch.bind(globalThis);
const isTransientSupabaseResponse = (response: Response) =>
  response.status === 502 || response.status === 503 || response.status === 504;
const wait = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

const resilientFetch: typeof fetch = async (input, init) => {
  let response: Response | null = null;
  let lastError: unknown = null;

  // PGRST002 ocorre enquanto o PostgREST recompõe o schema cache. Repetir a
  // requisição evita que uma oscilação de poucos segundos vire erro de tela.
  for (let attempt = 0; attempt < 4; attempt += 1) {
    try {
      // Requests podem conter um body stream (RPC em POST); cada tentativa
      // precisa de um clone para não reutilizar um stream já consumido.
      const retryInput = input instanceof Request ? input.clone() : input;
      response = await nativeFetch(retryInput, init);
      if (!isTransientSupabaseResponse(response) || attempt === 3) break;
      await wait(350 * (2 ** attempt));
    } catch (error) {
      lastError = error;
      if (attempt === 3) break;
      await wait(350 * (2 ** attempt));
    }
  }

  if (response) return response;

  console.warn('[Supabase] Falha de rede:', lastError);
  return new Response(
    JSON.stringify({
      message: 'Falha de rede ao consultar o Supabase.',
      details: lastError instanceof Error ? lastError.message : 'Network request failed',
    }),
    {
      status: 503,
      headers: { 'Content-Type': 'application/json' },
    },
  );
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: resilientFetch,
  },
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
});
