// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const FALLBACK_SUPABASE_URL = 'https://wxkkpjpqyrygglbuogsd.supabase.co';
const FALLBACK_SUPABASE_PUBLISHABLE_KEY =
  'sb_publishable_Zh6H3y8GJ2J_wkRVXxyTng_eylbCAVM';

// Se o bundle for publicado sem as variáveis Vite, usamos o projeto de produção
// atual para evitar que o cliente caia silenciosamente em um projeto legado.
export const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || FALLBACK_SUPABASE_URL;
export const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || FALLBACK_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Supabase client could not be initialized.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
});

// A árvore estruturada é complementar ao conteúdo principal da apostila.
// Se esse RPC falhar (por autenticação, RLS ou estrutura incompleta), a tela
// ainda precisa conseguir exibir `apostilas.content` e `apostila_pages`.
// O tratamento fica restrito a este RPC; os demais RPCs continuam propagando erros.
const originalRpc = supabase.rpc.bind(supabase);
(supabase as typeof supabase & { rpc: typeof supabase.rpc }).rpc = ((fn: string, args?: unknown, options?: unknown) => {
  const result = originalRpc(fn as never, args as never, options as never) as Promise<{ data: unknown; error: unknown | null }>;
  if (fn !== 'get_apostila_reader_tree') return result as never;
  return result.then((response) => (
    response.error ? { data: null, error: null } : response
  )) as never;
}) as typeof supabase.rpc;
